"""
generate.py  –  /generate endpoint (stub)

Accepts a multipart form with:
  - image: UploadFile  (the user's 2D image)
  - style_prompt: str  (optional style description)

Returns a mock response for now. The Tripo AI + Groq integration
will be added in the next step of development.
"""

import uuid
from fastapi import APIRouter, UploadFile, File, Form, HTTPException
from pydantic import BaseModel

from app.services.groq_service import generate_nft_metadata
from app.services.tripo_service import create_3d_task, wait_for_task

router = APIRouter()


# ── Response schema ───────────────────────────────────────────────────────────

class NftAttribute(BaseModel):
    trait_type: str
    value: str


class NftMetadata(BaseModel):
    name: str
    description: str
    image: str
    model_url: str
    attributes: list[NftAttribute]


class GenerateResponse(BaseModel):
    task_id: str
    model_url: str
    metadata: NftMetadata


# ── Endpoint ──────────────────────────────────────────────────────────────────

@router.post("/generate", response_model=GenerateResponse)
async def generate_nft(
    image: UploadFile = File(..., description="2D input image (PNG/JPG/WEBP)"),
    style_prompt: str = Form("", description="Optional style description"),
) -> GenerateResponse:
    """
    Generates a 3D model using Tripo AI and metadata via Groq.
    """
    if image.content_type not in ("image/png", "image/jpeg", "image/webp"):
        raise HTTPException(
            status_code=422,
            detail="Unsupported image format. Use PNG, JPEG, or WEBP.",
        )

    # 1. Read Image Bytes
    image_bytes = await image.read()

    # 2. Start Tripo AI Task
    tripo_task_id = await create_3d_task(image_bytes, content_type=image.content_type)
    if not tripo_task_id:
        raise HTTPException(status_code=500, detail="Failed to initiate 3D generation.")

    # 3. Generate metadata via Groq Vision — passes the actual image
    ai_metadata = await generate_nft_metadata(
        style_prompt=style_prompt,
        image_bytes=image_bytes,
        content_type=image.content_type,
    )

    # 4. Wait for 3D model (Polling)
    # Note: In a production app, you might use WebSockets or Webhooks.
    # For this MVP, we poll for completion.
    model_url = await wait_for_task(tripo_task_id)
    
    if not model_url:
        # Fallback or error
        model_url = "https://example.com/fallback.glb" 

    # 5. Combine everything
    final_metadata = NftMetadata(
        name=ai_metadata.get("name", f"NFT_{tripo_task_id[:8]}"),
        description=ai_metadata.get("description", "A unique 3D asset generated by AI."),
        image="https://gateway.pinata.cloud/ipfs/placeholder", # TODO: Generate preview
        model_url=model_url,
        attributes=[NftAttribute(**attr) for attr in ai_metadata.get("attributes", [])]
    )

    return GenerateResponse(
        task_id=tripo_task_id,
        model_url=model_url,
        metadata=final_metadata,
    )


